services:
  config-service:
    container_name: config-service
    build:
      dockerfile: ./config-service/Dockerfile
    ports:
      - "8088:8088"
    networks:
      - microservice-network
    healthcheck:
      test: "curl -f http://localhost:8088/discovery-service/default"
      interval: 5s
      timeout: 3s
      retries: 10

  discovery-service:
    container_name: discovery-service
    build:
      dockerfile: ./discovery-service/Dockerfile
    ports:
      - "8061:8061"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
